/**
 * Sidebar for the UnrestCoreSystem docs site.
 *
 * This file is hand-written rather than autogenerated so that `docs/` can stay a flat
 * folder of files with no front matter of its own. Grouping, ordering and labels all
 * live here; the Markdown sources are untouched.
 *
 * Conventions:
 *   - every label carries `· EN` or `· ID`, because the docs are written in two
 *     languages and nothing has been translated;
 *   - the Proposals category is separate from everything else, and its landing page
 *     says so, because it describes code that does not exist yet.
 *
 * Maintenance note: because this sidebar is explicit, a NEW file dropped into docs/
 * still gets its own URL but will NOT appear in the sidebar until it is added below.
 * That is the trade for keeping the Markdown sources free of front matter.
 */
module.exports = {
    defaultSidebar: [
        {
            type: "doc",
            id: "intro",
            label: "Start here · EN/ID",
        },
        {
            type: "category",
            label: "Guides",
            collapsed: false,
            link: {
                type: "generated-index",
                title: "Guides",
                description:
                    "Read in this order. These pages describe the framework as it exists in src/ today.",
                slug: "/category/guides",
            },
            items: [
                { type: "doc", id: "MENTAL-MODEL", label: "Model Mental · ID" },
                { type: "doc", id: "GETTING-STARTED", label: "Getting Started · EN" },
                { type: "doc", id: "ARCHITECTURE", label: "Architecture · EN" },
            ],
        },
        {
            type: "category",
            label: "Reference",
            collapsed: false,
            link: {
                type: "generated-index",
                title: "Reference",
                description:
                    "Look-up material, not front-to-back reading. These pages describe the framework as it exists in src/ today.",
                slug: "/category/reference",
            },
            items: [
                { type: "doc", id: "UI-BINDING", label: "UI Binding · EN" },
                { type: "doc", id: "REMOTE-SECURITY", label: "Remote Security · EN" },
            ],
        },
        {
            type: "category",
            label: "Proposals — not implemented",
            collapsed: false,
            link: {
                type: "generated-index",
                title: "Proposals — not implemented",
                description:
                    "Design work, not documentation. Nothing described in this section exists in src/. Do not read these pages as a description of shipped behaviour. — Rancangan, bukan dokumentasi: tidak ada satu pun yang dibahas di bagian ini sudah ada di src/.",
                slug: "/category/proposals",
            },
            items: [
                { type: "doc", id: "PROPOSAL-CONTROLS", label: "Controls (v2) · ID" },
                { type: "doc", id: "PROPOSAL-TRANSPORT", label: "Transport · ID" },
            ],
        },
    ],
};
